# Generated by Django 3.2.25 on 2025-03-18 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='is_record',
            field=models.BooleanField(default=False, verbose_name='是否录制'),
        ),
        migrations.CreateModel(
            name='MeetingParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participants', models.TextField(blank=True, default='', null=True, verbose_name='会议议程')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.meeting')),
            ],
            options={
                'verbose_name': 'meetings_participants',
                'verbose_name_plural': 'meetings_participants',
                'db_table': 'meetings_participants',
            },
        ),
    ]
