# Generated by Django 4.2.22 on 2025-06-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20250318_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=32, verbose_name='会议id')),
                ('vid', models.CharField(blank=True, max_length=128, null=True, verbose_name='B站回放会议id')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'meetings_cache',
                'verbose_name_plural': 'meetings_cache',
                'db_table': 'meetings_cache',
            },
        ),
    ]
