# Generated by Django 4.2.23 on 2025-08-15 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_meetingcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingBiliRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=32, verbose_name='会议id')),
                ('status', models.SmallIntegerField(choices=[(0, '初始化'), (1, '完成请求翻译'), (10, '已经上传完成')], default=0, verbose_name='上传状态')),
                ('replay_url', models.CharField(blank=True, max_length=128, null=True, verbose_name='回放会议url')),
            ],
            options={
                'verbose_name': 'meetings_records_bili',
                'verbose_name_plural': 'meetings_records_bili',
                'db_table': 'meetings_records_bili',
            },
        ),
        migrations.CreateModel(
            name='MeetingObsRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=32, verbose_name='会议id')),
                ('status', models.SmallIntegerField(choices=[(0, '初始化'), (1, '完成请求翻译'), (10, '已经上传完成')], default=0, verbose_name='上传状态')),
                ('text_vtt_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='文本vtt地址')),
                ('text_json_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='文本json地址')),
                ('text_video_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='文本video地址')),
                ('text_picture_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='文本picture地址')),
                ('topic_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='议题切分地址')),
            ],
            options={
                'verbose_name': 'meetings_records_obs',
                'verbose_name_plural': 'meetings_records_obs',
                'db_table': 'meetings_records_obs',
            },
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='replay_url',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='upload_status',
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_cycle',
            field=models.BooleanField(default=False, verbose_name='是否周期性会议'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='会议日期'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='会议结束时间'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='会议开始时间'),
        ),
        migrations.CreateModel(
            name='MeetingCycleSubMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=32, verbose_name='会议id')),
                ('sub_id', models.CharField(max_length=32, verbose_name='子会议的ID')),
                ('date', models.CharField(max_length=32, verbose_name='会议日期')),
                ('start', models.CharField(max_length=32, verbose_name='会议开始时间')),
                ('end', models.CharField(max_length=32, verbose_name='会议结束时间')),
                ('meeting', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_sub_meeting', to='meeting.meeting')),
            ],
            options={
                'verbose_name': 'meetings_cycle_sub_meeting',
                'verbose_name_plural': 'meetings_cycle_sub_meeting',
                'db_table': 'meetings_cycle_sub_meeting',
            },
        ),
        migrations.CreateModel(
            name='MeetingCycleDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mid', models.CharField(max_length=32, verbose_name='会议id')),
                ('start_date', models.CharField(max_length=32, verbose_name='会议开始日期')),
                ('end_date', models.CharField(max_length=32, verbose_name='会议结束日期')),
                ('start', models.CharField(max_length=32, verbose_name='会议开始时间')),
                ('end', models.CharField(max_length=32, verbose_name='会议结束时间')),
                ('cycle_type', models.SmallIntegerField(choices=[(0, 'Day'), (1, 'Week'), (2, 'Month')], verbose_name='周期类型')),
                ('interval', models.IntegerField(blank=True, null=True, verbose_name='子会议时间间隔')),
                ('point', models.CharField(blank=True, max_length=32, null=True, verbose_name='周期内的会员召开时间')),
                ('meeting', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_date', to='meeting.meeting')),
            ],
            options={
                'verbose_name': 'meetings_cycle_date',
                'verbose_name_plural': 'meetings_cycle_date',
                'db_table': 'meetings_cycle_date',
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='bili_records',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.meetingbilirecords'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='obs_records',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meeting.meetingobsrecords'),
        ),
    ]
