# Generated by Django 4.2.23 on 2025-08-26 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_meetingbilirecords_meetingobsrecords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='bili_records',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='obs_records',
        ),
        migrations.AddField(
            model_name='meetingbilirecords',
            name='meeting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_bili', to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='meetingbilirecords',
            name='sub_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='子会议的ID'),
        ),
        migrations.AddField(
            model_name='meetingobsrecords',
            name='meeting',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cycle_obs', to='meeting.meeting'),
        ),
        migrations.AddField(
            model_name='meetingobsrecords',
            name='sub_id',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='子会议的ID'),
        ),
    ]
