# Generated by Django 4.2.25 on 2025-10-31 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_remove_meeting_bili_records_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingobsrecords',
            name='text_picture_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='文本video图片地址'),
        ),
    ]
