# Generated by Django 4.2.27 on 2026-03-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_alter_meetingobsrecords_text_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='是否闭门会议'),
        ),
    ]
