# Generated by Django 4.2.29 on 2026-03-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_meeting_is_private'),
    ]

    operations = [
        # Meeting 模型字段
        migrations.AddField(
            model_name='meeting',
            name='is_ongoing',
            field=models.BooleanField(default=False, verbose_name='是否正在进行中'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='ongoing_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='状态更新时间'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_overtime',
            field=models.BooleanField(default=False, verbose_name='是否超时'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='overtime_detected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='超时检测时间'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='warning_email_sent',
            field=models.BooleanField(default=False, verbose_name='是否已发送预警邮件'),
        ),
        # MeetingCycleSubMeeting 模型字段
        migrations.AddField(
            model_name='meetingcyclesubmeeting',
            name='is_ongoing',
            field=models.BooleanField(default=False, verbose_name='是否正在进行中'),
        ),
        migrations.AddField(
            model_name='meetingcyclesubmeeting',
            name='ongoing_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='状态更新时间'),
        ),
        migrations.AddField(
            model_name='meetingcyclesubmeeting',
            name='is_overtime',
            field=models.BooleanField(default=False, verbose_name='是否超时'),
        ),
        migrations.AddField(
            model_name='meetingcyclesubmeeting',
            name='overtime_detected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='超时检测时间'),
        ),
        migrations.AddField(
            model_name='meetingcyclesubmeeting',
            name='warning_email_sent',
            field=models.BooleanField(default=False, verbose_name='是否已发送预警邮件'),
        ),
    ]