# Generated by Django 4.2.29 on 2026-04-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_meeting_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束'), (3, '已超时'), (4, '已取消')], default=0, verbose_name='会议实时状态'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='状态更新时间'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='warning_email_sent',
            field=models.BooleanField(default=False, verbose_name='是否已发送预警邮件'),
        ),
        migrations.AddField(
            model_name='meetingcyclesubmeeting',
            name='status',
            field=models.SmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已结束'), (3, '已超时'), (4, '已取消')], default=0, verbose_name='子会议实时状态'),
        ),
        migrations.AddField(
            model_name='meetingcyclesubmeeting',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='状态更新时间'),
        ),
        migrations.AddField(
            model_name='meetingcyclesubmeeting',
            name='warning_email_sent',
            field=models.BooleanField(default=False, verbose_name='是否已发送预警邮件'),
        ),
    ]
